swagger: '2.0'
# Added by API Auto Mocking Plugin
host: lynksolutions.tuks
basePath: /lynksolutions/Watchdog/1.0.0
schemes:
 - https
 - http
info:
  description: |
    This is a sample Petstore server.  You can find 
    out more about Swagger at 
    [http://swagger.io](http://swagger.io) or on 
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: 1.0.0
  title: Watchdog Security
  contact:
    email: lynksolutions.tuks@outlook.com
paths:
  /user:
    post:
      summary: Retrieve user data
  /user/gettoken:
    post:
      summary: Retrieve JWT Token for user
  /user/getcameras:
    post:
      summary: Retrieve a list of Cameras belonging to the User
  /user/historical:
    get:
      summary: Fetches the historical footage of the user
      consumes:
        - application/json
      produces:
          - application/json
      parameters:
        - in: body
          name: user_id
          description: ID of the user
          required: true
      responses:
        200:
          description: OK
        405:
          description: invalid input
  /hcp:
    post:
      summary: get a live stream from the ip camera
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: ipcamera
        description: get ip address of camera
        required: true
      responses:
        200:
          description: OK
        405:
          description: invalid input
  /hcp/controlpanelconfig:
    post:
      summary: configures the home control panel
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: body
        name: controlpanel
        description: The control panel to configure.
        schema:
            type: object
            required:
                - user_id
        properties:
                user_id:
                    type: string
        responses:
            200:
             description: OK
            401:
             description: unauthorised
            500:
             description: server error
  /hcp/uploadclip:
    post:
      summary: uploads periodically saved clips from ip camera
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: body
        name: clipupload
        description: The periodical video clip to upload.
        schema:
              type: object
              required:
                - time
                - path #the path to the S3 bucket
                - camera_id
                - tag
                - expiration
        properties:
                  time:
                    type: string
                    format: date-time
                  path:
                    type: string
                  camera_id:
                    type: string
                  tag:
                    type: string
                  expiration:
                    type: string
                    format: date-time
      responses:
            200:
              description: OK
            401:
              description: unauthorised
            500:
              description: server error
  /hcp/detectintruder:
    post:
      summary: used for intruder detection
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: intruder_image
          description: The intruder data.
          schema:
            type: object
            required:
              - image_detected
              - camera_detected_on
          properties:
            image_detected:
              type: string
            camera_detected_on:
              type: string
      responses:
        200:
          description: OK
        401:
          description: unauthorised
        500:
          description: server error
  /hcp/registersite:
    post:
      summary: uploads periodically saved clips from ip camera
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: controlpanel
          description: The home control panel to register.
          schema:
            type: object
            required:
              - site_id
          properties:
            site_id:
              type: object
      responses:
        200:
          description: OK
        401:
          description: unauthorised
        500:
          description: server error
  /hcp/registercamera:
    post:
      summary: registers a camera to a control panel
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: IPcamera
          description: The IP camera to register.
          schema:
            type: object
            required:
              - camera_id
          properties:
            camera_id:
              type: object
      responses:
        200:
          description: OK
        401:
          description: unauthorised
        500:
          description: server error


 
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

