AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Watchdog API

  The interface for the Watchdog Database for communication between Front and Back
  end

  '
Globals:
  Function:
    Timeout: 3
Resources:
  WatchdogApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: beta
      DefinitionUri: s3://watchdog-api-deployment-workspace/ff43e0c504dfe09116d109e126d36262
