AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Watchdog API

  The interface for the Watchdog Database for communication between Front and Back end

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WatchdogApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: beta
      DefinitionUri: ./swagger.yaml